[gcp_service_account]
type = "service_account"
project_id = "mrr-project-447111"
private_key_id = "8eb19136c105c3238df12ec3105495498dedb420"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCRXtoAzniVMfZ/
ZquT9aZ2a/dK2F3RaZPj3oo2uLRM7Kd/QnaOUUW3AOXELaKCcSlRfRwATiLyvUeq
WMUpx0suSXtX6tnKkmiLPbgJLait6M694BOppTmRTh+t8rMo9mz5ev5Yy1b1iHQc
1awlvLa6qXn2cIa61a+Ls0tOQzVgQ3yyOeTjckbieiNy/2mzwF1Um9d7SkCZYH/q
lzTc3ir2qTZzWiFTlCRn6bxpIBxWWN+dhRYufUpRhob8PG+55H4jvMEUzRryhTMo
ww0T5b/3tPi6M6+gdYg+VFNzf3sMbgzBEw/mc/nQdYEekjOZVJx8jtQm1FChp1Ak
bYGEH1vZAgMBAAECggEALjxxcTU6dBWWlbHlm6NTpTG0z0jfGiaO47iZ1ErOCfNx
WNAeXiiqWEkAS3PKTtvILQNyXwR7KCKcwykF2MJq/pdflDh9uej0OGlSehTcJCg6
bXjyOBB1rWogOFbLthke0wDUGhDeoSyb5bnuTXhm1BroUEI9D/q8IV5O8t78gJer
v+F1DhmYguFmtA5VRt6Hr9FOooqWkuj4fqj78lL4rR9GbiiPkJUfSwMmZezKLuuY
+hUlaZz9/FbcbuQARRG+9SjG4reQCFK3bLw9VxEiijL+QcDWKWxfMY9llv+1pCGt
59IvtKxgSThnmkt2jYpfJ9jwOIH0ANOzc8tQKJL7IwKBgQDA/KBeIvlP9Jk4MRcq
hJt0BeMRKCAC5pOLdhknKxzrS7zG07o28keqDZumVb5Og4ES8C2W4zJ+znhiHrAD
bvgaBti2q8Y5fFRfki/7brA1xUO0vYE03faW4Na/vybPZIP8f80jdI79gHI0vat+
UBIF8zfccMw3GxHeie3Pg3hZIwKBgQDA1hNMI1kty/bri+1HMf7vwEBTRj+UHEqS
BiZ3niedQ2EqA2YlrElqTjCqzYEugzs7K7p0bySOOT1bSALDyNztrZy0GLaTWnAU
M4j9uJuiSgECAI1qTjvBgvENGGSshH81ZNt/qGeP5z5xEqyFSlRbWYIyhwW6sPoJ
lHi1MOLM0wKBgQCgaZy3guSvBEbTwWJbMiyxLS+IFE0/e/+Kfdj8iMaaArNgpZ90
isDs5jDJ+x2bz41be465jBJt+xtvm8h8oiHSKHy8ol27bNAJPM9rdJ89osHbm2Wp
1xJgaXW3nqEY5JkdKfIPFZTBvKGxmzLQZKgGkBuPvabR60tYKlglFEfV9wKBgQCG
J+kA/U6bl9zO/mgzMcskzOFzjdnJlu0iLfkxGuyAclH0wqyb5QKmXINrMNGApHfe
sItlWbVa5OOUz8Jspx9ck34DpXXPigmTZE8YBQjxnP6af/viS08zT3+YFrJje0Js
ySAT7fsumDhOvikcChwp+VmlAV6xBVLOu2ZG2B3RVQKBgQCqZwuq8CgqUSsXeAUM
wrJ/NURczJuzewUzvyILcmNvyFYt00XIePSOF2d0u03CoHIIH4jkQJC7yxie7Of8
GZopqoDzR1kwo4ASKbagMoNkH5hBOZHRaA+qeGDLYJoixNnYvL1DGKj3629i9gnS
TtJyWrJwDCcQFZiMUPeVqcCPJA==
-----END PRIVATE KEY-----"""
client_email = "ankitshetty@mrr-project-447111.iam.gserviceaccount.com"
client_id = "105170377531470477493"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ankitshetty%40mrr-project-447111.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
